version: '3.8'

services:
  # n8n orchestrator
  n8n:
    image: n8nio/n8n:latest
    container_name: whatsapp-copilot-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678
      - GENERIC_TIMEZONE=UTC
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/workflows:/home/node/.n8n/workflows
    depends_on:
      - agenta
      - agentb
      - chroma
    networks:
      - copilot-network

  # Agent A - Knowledge Agent
  agenta:
    build:
      context: ./agents/agentA_knowledge
      dockerfile: Dockerfile
    container_name: whatsapp-copilot-agenta
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
      - LOG_LEVEL=INFO
    volumes:
      - ./data/chroma:/app/data/chroma
    depends_on:
      - chroma
    networks:
      - copilot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Agent B - Dealflow Agent  
  agentb:
    build:
      context: ./agents/agentB_dealflow
      dockerfile: Dockerfile
    container_name: whatsapp-copilot-agentb
    ports:
      - "8002:8002"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=INFO
    networks:
      - copilot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Chroma Vector Database
  chroma:
    image: chromadb/chroma:latest
    container_name: whatsapp-copilot-chroma
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    volumes:
      - ./data/chroma:/chroma/chroma
    networks:
      - copilot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Intent Classifier Service (shared)
  intent-classifier:
    build:
      context: ./shared
      dockerfile: Dockerfile
    container_name: whatsapp-copilot-classifier
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=INFO
    networks:
      - copilot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  copilot-network:
    driver: bridge

volumes:
  n8n_data:
    driver: local
